const ActionType = {
    // GET_ALL_POKEMON: 'GET_ALL_POKEMON',
    // GET_SELECTED_POKEMON: 'GET_SELECTED_POKEMON',
    GET_SELECTED_WILD_POKEMON: 'GET_SELECTED_WILD_POKEMON',
    GET_DETAIL_POKEMON_DATA: 'GET_DETAIL_POKEMON_DATA',
    GET_SELECTED_WILD_POKEMON_SPECIES: 'GET_SELECTED_WILD_POKEMON_SPECIES',
    GET_POKEMON: 'GET_POKEMON',
    LOAD_MORE_POKEMON: "LOAD_MORE_POKEMON",
    CATCH_POKEMON: 'CATCH_POKEMON',
    GET_ALL_POKEMON_OWNED: 'GET_ALL_POKEMON_OWNED',
    GET_DEFAULT_SPECIES_POKEMON: 'GET_DEFAULT_SPECIES_POKEMON',
    GET_SELECTED_OWNED_POKEMON: 'GET_SELECTED_OWNED_POKEMON',
    RELEASE_POKEMON_OWNED: 'RELEASE_POKEMON_OWNED',
    RELOAD_POKEMON_LOADED_LIST: 'RELOAD_POKEMON_LOADED_LIST'
}

export default ActionType;